# .github/workflows/deploy.yml
name: Deploy SlimmerMetAI to Antagonist

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, curl, gd, pdo_mysql
        coverage: none

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

    # --- Debug SSH Configuration ---
    - name: Debug SSH Configuration
      run: |
        echo "🔍 Debugging SSH Configuration..."
        echo "Host: 31.184.80.250"
        echo "Port: 22"
        echo "User: ${{ secrets.SSH_USER }}"
        echo "Production Path: /home/deb133403n2/domains/slimmermetai.com"
        
        # Validate required secrets
        if [ -z "${{ secrets.SSH_USER }}" ] || [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
          echo "❌ One or more required secrets are missing"
          exit 1
        fi
        
        echo "✅ All required secrets are configured"

    # --- Test SSH Connection ---
    - name: Test SSH Connection
      run: |
        echo "🔑 Testing SSH Connection..."
        
        # Setup SSH
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        
        # Test connection
        ssh -o StrictHostKeyChecking=no \
            -o ConnectTimeout=10 \
            -p 22 \
            -i ~/.ssh/deploy_key \
            ${{ secrets.SSH_USER }}@31.184.80.250 \
            "echo '🔒 SSH connection successful!' && ls -la /home/deb133403n2/domains/slimmermetai.com"

    # --- Deploy to Production ---
    - name: Deploy to Production
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete --exclude='.env*' --exclude='.git*' --exclude='node_modules' --exclude='storage/logs/*' --exclude='.ssh'
        path: ./
        remote_path: /home/deb133403n2/domains/slimmermetai.com/
        remote_host: 31.184.80.250
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: 22

    - name: Post-Deployment Tasks
      run: |
        echo "📝 Running post-deployment tasks..."
        ssh -o StrictHostKeyChecking=no \
            -p 22 \
            -i ~/.ssh/deploy_key \
            ${{ secrets.SSH_USER }}@31.184.80.250 \
            "cd /home/deb133403n2/domains/slimmermetai.com && \
             cp .env.production .env && \
             chmod -R 755 . && \
             find . -type f -exec chmod 644 {} \; && \
             chmod -R 775 storage && \
             chmod -R 775 public/uploads" 