# .github/workflows/deploy.yml
name: Deploy SlimmerMetAI to Antagonist

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, curl, gd, pdo_mysql
        coverage: none

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache Composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-dev --optimize-autoloader

    # --- Deployment naar Productie (main branch) ---
    - name: Deploy public_html to Production
      if: github.ref == 'refs/heads/main'
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: ./public_html/
        remote_path: ${{ secrets.PRODUCTION_PATH }}/public_html/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}

    - name: Deploy includes to Production
      if: github.ref == 'refs/heads/main'
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: ./includes/
        remote_path: ${{ secrets.PRODUCTION_PATH }}/includes/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}

    - name: Deploy vendor to Production
      if: github.ref == 'refs/heads/main'
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr --delete
        path: ./vendor/
        remote_path: ${{ secrets.PRODUCTION_PATH }}/vendor/
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }}

    - name: Deploy .env to Production
      if: github.ref == 'refs/heads/main'
      uses: burnett01/rsync-deployments@7.0.1
      with:
        switches: -avzr
        path: ./.env
        remote_path: ${{ secrets.PRODUCTION_PATH }}/.env
        remote_host: ${{ secrets.SSH_HOST }}
        remote_user: ${{ secrets.SSH_USER }}
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
        remote_port: ${{ secrets.SSH_PORT }} 